2023-09-15 23:28:28,021 INFO    StreamThr :2242593 [internal.py:wandb_internal():86] W&B internal server running at pid: 2242593, started at: 2023-09-15 23:28:28.020120
2023-09-15 23:28:28,022 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: status
2023-09-15 23:28:28,051 INFO    WriterThread:2242593 [datastore.py:open_for_write():85] open: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230915_232828-mx8e5cga/run-mx8e5cga.wandb
2023-09-15 23:28:28,053 DEBUG   SenderThread:2242593 [sender.py:send():369] send: header
2023-09-15 23:28:28,070 DEBUG   SenderThread:2242593 [sender.py:send():369] send: run
2023-09-15 23:28:28,443 INFO    SenderThread:2242593 [dir_watcher.py:__init__():211] watching files in: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230915_232828-mx8e5cga/files
2023-09-15 23:28:28,443 INFO    SenderThread:2242593 [sender.py:_start_run_threads():1100] run started: mx8e5cga with start time 1694816908.050054
2023-09-15 23:28:28,443 DEBUG   SenderThread:2242593 [sender.py:send_request():396] send_request: summary_record
2023-09-15 23:28:28,444 INFO    SenderThread:2242593 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-09-15 23:28:28,450 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: check_version
2023-09-15 23:28:28,451 DEBUG   SenderThread:2242593 [sender.py:send_request():396] send_request: check_version
2023-09-15 23:28:28,525 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: run_start
2023-09-15 23:28:28,531 DEBUG   HandlerThread:2242593 [system_info.py:__init__():31] System info init
2023-09-15 23:28:28,531 DEBUG   HandlerThread:2242593 [system_info.py:__init__():46] System info init done
2023-09-15 23:28:28,531 INFO    HandlerThread:2242593 [system_monitor.py:start():181] Starting system monitor
2023-09-15 23:28:28,531 INFO    SystemMonitor:2242593 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-09-15 23:28:28,532 INFO    HandlerThread:2242593 [system_monitor.py:probe():201] Collecting system info
2023-09-15 23:28:28,532 INFO    SystemMonitor:2242593 [interfaces.py:start():190] Started cpu monitoring
2023-09-15 23:28:28,532 INFO    SystemMonitor:2242593 [interfaces.py:start():190] Started disk monitoring
2023-09-15 23:28:28,533 INFO    SystemMonitor:2242593 [interfaces.py:start():190] Started gpu monitoring
2023-09-15 23:28:28,534 INFO    SystemMonitor:2242593 [interfaces.py:start():190] Started memory monitoring
2023-09-15 23:28:28,534 INFO    SystemMonitor:2242593 [interfaces.py:start():190] Started network monitoring
2023-09-15 23:28:28,564 DEBUG   HandlerThread:2242593 [system_info.py:probe():195] Probing system
2023-09-15 23:28:28,566 DEBUG   HandlerThread:2242593 [system_info.py:_probe_git():180] Probing git
2023-09-15 23:28:28,581 DEBUG   HandlerThread:2242593 [system_info.py:_probe_git():188] Probing git done
2023-09-15 23:28:28,581 DEBUG   HandlerThread:2242593 [system_info.py:probe():240] Probing system done
2023-09-15 23:28:28,581 DEBUG   HandlerThread:2242593 [system_monitor.py:probe():210] {'os': 'Linux-5.15.0-76-generic-x86_64-with-glibc2.35', 'python': '3.10.11', 'heartbeatAt': '2023-09-15T22:28:28.564840', 'startedAt': '2023-09-15T22:28:28.003196', 'docker': None, 'cuda': None, 'args': ('--model_name', 'Entangled18', '--project_name', 'Elodea', '--root', '/local/scratch/jrs596/dat/ElodeaProject', '--data_dir', 'FasterRCNN_output/Rudders_split', '--arch', 'resnet18', '--min_epochs', '10', '--batch_size', '32', '--patience', '20', '--weights', '/local/scratch/jrs596/dat/models/PlantNotPlant_SemiSup.pkl', '--save', 'both', '--entity', 'frankslab'), 'state': 'running', 'program': '/home/userfs/j/jrs596/scripts/Entangled/Torch_Custom_CNNs2.2.1.py', 'codePath': 'Torch_Custom_CNNs2.2.1.py', 'git': {'remote': 'git@github.com:jrsykes/Entangled.git', 'commit': 'dd36b1f71e53d67a140ff98d32b01aa90a307e46'}, 'email': 'jamie.sykes@york.ac.uk', 'root': '/home/userfs/j/jrs596/scripts/Entangled', 'host': 'csgpu5', 'username': 'jrs596', 'executable': '/local/scratch/jrs596/envs/torch3/bin/python', 'cpu_count': 6, 'cpu_count_logical': 12, 'cpu_freq': {'current': 3988.919916666667, 'min': 800.0, 'max': 4700.0}, 'cpu_freq_per_core': [{'current': 4299.999, 'min': 800.0, 'max': 4700.0}, {'current': 4167.013, 'min': 800.0, 'max': 4700.0}, {'current': 3700.0, 'min': 800.0, 'max': 4700.0}, {'current': 4300.0, 'min': 800.0, 'max': 4700.0}, {'current': 4300.0, 'min': 800.0, 'max': 4700.0}, {'current': 4300.028, 'min': 800.0, 'max': 4700.0}, {'current': 3700.0, 'min': 800.0, 'max': 4700.0}, {'current': 3700.0, 'min': 800.0, 'max': 4700.0}, {'current': 4299.999, 'min': 800.0, 'max': 4700.0}, {'current': 3700.0, 'min': 800.0, 'max': 4700.0}, {'current': 3700.0, 'min': 800.0, 'max': 4700.0}, {'current': 3700.0, 'min': 800.0, 'max': 4700.0}], 'disk': {'total': 427.3533935546875, 'used': 26.312114715576172}, 'gpu': 'NVIDIA GeForce GTX 1080 Ti', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1080 Ti', 'memory_total': 11811160064}, {'name': 'Quadro P6000', 'memory_total': 25769803776}], 'memory': {'total': 31.279434204101562}}
2023-09-15 23:28:28,582 INFO    HandlerThread:2242593 [system_monitor.py:probe():211] Finished collecting system info
2023-09-15 23:28:28,582 INFO    HandlerThread:2242593 [system_monitor.py:probe():214] Publishing system info
2023-09-15 23:28:28,582 DEBUG   HandlerThread:2242593 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-09-15 23:28:28,583 DEBUG   HandlerThread:2242593 [system_info.py:_save_pip():67] Saving pip packages done
2023-09-15 23:28:28,583 DEBUG   HandlerThread:2242593 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-09-15 23:28:29,444 INFO    Thread-12 :2242593 [dir_watcher.py:_on_file_created():272] file/dir created: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230915_232828-mx8e5cga/files/wandb-summary.json
2023-09-15 23:28:29,445 INFO    Thread-12 :2242593 [dir_watcher.py:_on_file_created():272] file/dir created: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230915_232828-mx8e5cga/files/conda-environment.yaml
2023-09-15 23:28:29,445 INFO    Thread-12 :2242593 [dir_watcher.py:_on_file_created():272] file/dir created: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230915_232828-mx8e5cga/files/requirements.txt
2023-09-15 23:28:30,323 DEBUG   HandlerThread:2242593 [system_info.py:_save_conda():86] Saving conda packages done
2023-09-15 23:28:30,325 INFO    HandlerThread:2242593 [system_monitor.py:probe():216] Finished publishing system info
2023-09-15 23:28:30,326 DEBUG   SenderThread:2242593 [sender.py:send():369] send: files
2023-09-15 23:28:30,326 INFO    SenderThread:2242593 [sender.py:_save_file():1354] saving file wandb-metadata.json with policy now
2023-09-15 23:28:30,335 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: stop_status
2023-09-15 23:28:30,335 DEBUG   SenderThread:2242593 [sender.py:send_request():396] send_request: stop_status
2023-09-15 23:28:30,615 DEBUG   SenderThread:2242593 [sender.py:send():369] send: telemetry
2023-09-15 23:28:30,644 DEBUG   SenderThread:2242593 [sender.py:send():369] send: telemetry
2023-09-15 23:28:30,644 DEBUG   SenderThread:2242593 [sender.py:send():369] send: files
2023-09-15 23:28:30,644 INFO    SenderThread:2242593 [sender.py:_save_file():1354] saving file * with policy live
2023-09-15 23:28:30,834 INFO    wandb-upload_0:2242593 [upload_job.py:push():133] Uploaded file /tmp/tmpi8nzp97pwandb/xcthdqx1-wandb-metadata.json
2023-09-15 23:28:31,128 INFO    wandb-upload_2:2242593 [upload_job.py:push():133] Uploaded file /tmp/tmpi8nzp97pwandb/uqaypl7c-requirements.txt
2023-09-15 23:28:31,128 INFO    wandb-upload_1:2242593 [upload_job.py:push():133] Uploaded file /tmp/tmpi8nzp97pwandb/a5zdb1p9-config.yaml
2023-09-15 23:28:31,465 INFO    wandb-upload_5:2242593 [upload_job.py:push():133] Uploaded file /tmp/tmpi8nzp97pwandb/13blfn36-Entangled.py
2023-09-15 23:28:31,493 INFO    wandb-upload_8:2242593 [upload_job.py:push():133] Uploaded file /tmp/tmpi8nzp97pwandb/hzauh57f-README.md
2023-09-15 23:28:31,493 INFO    wandb-upload_3:2242593 [upload_job.py:push():133] Uploaded file /tmp/tmpi8nzp97pwandb/fjk3k2wf-conda-environment.yaml
2023-09-15 23:28:31,495 INFO    wandb-upload_6:2242593 [upload_job.py:push():133] Uploaded file /tmp/tmpi8nzp97pwandb/8qjqfo49-Entangled.yml
2023-09-15 23:28:31,516 INFO    wandb-upload_9:2242593 [upload_job.py:push():133] Uploaded file /tmp/tmpi8nzp97pwandb/1y7cyfzq-Torch_Custom_CNNs2.2.1.py
2023-09-15 23:28:31,522 INFO    wandb-upload_7:2242593 [upload_job.py:push():133] Uploaded file /tmp/tmpi8nzp97pwandb/rz7a3bma-Entangled_train.sh
2023-09-15 23:28:31,523 INFO    wandb-upload_4:2242593 [upload_job.py:push():133] Uploaded file /tmp/tmpi8nzp97pwandb/dc0xroaa-Detectron2_train.py
2023-09-15 23:28:31,616 INFO    wandb-upload_0:2242593 [upload_job.py:push():133] Uploaded file /tmp/tmpi8nzp97pwandb/w4sg7n1h-wandb-metadata.json
2023-09-15 23:28:33,664 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: status_report
2023-09-15 23:28:36,965 DEBUG   SenderThread:2242593 [sender.py:send():369] send: exit
2023-09-15 23:28:36,965 INFO    SenderThread:2242593 [sender.py:send_exit():574] handling exit code: 1
2023-09-15 23:28:36,966 INFO    SenderThread:2242593 [sender.py:send_exit():576] handling runtime: 8
2023-09-15 23:28:36,969 INFO    SenderThread:2242593 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-09-15 23:28:36,969 INFO    SenderThread:2242593 [sender.py:send_exit():582] send defer
2023-09-15 23:28:36,969 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: defer
2023-09-15 23:28:36,969 INFO    HandlerThread:2242593 [handler.py:handle_request_defer():170] handle defer: 0
2023-09-15 23:28:36,970 DEBUG   SenderThread:2242593 [sender.py:send_request():396] send_request: defer
2023-09-15 23:28:36,970 INFO    SenderThread:2242593 [sender.py:send_request_defer():598] handle sender defer: 0
2023-09-15 23:28:36,970 INFO    SenderThread:2242593 [sender.py:transition_state():602] send defer: 1
2023-09-15 23:28:36,970 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: defer
2023-09-15 23:28:36,970 INFO    HandlerThread:2242593 [handler.py:handle_request_defer():170] handle defer: 1
2023-09-15 23:28:36,971 DEBUG   SenderThread:2242593 [sender.py:send_request():396] send_request: defer
2023-09-15 23:28:36,971 INFO    SenderThread:2242593 [sender.py:send_request_defer():598] handle sender defer: 1
2023-09-15 23:28:36,971 INFO    SenderThread:2242593 [sender.py:transition_state():602] send defer: 2
2023-09-15 23:28:36,971 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: defer
2023-09-15 23:28:36,971 INFO    HandlerThread:2242593 [handler.py:handle_request_defer():170] handle defer: 2
2023-09-15 23:28:36,972 INFO    HandlerThread:2242593 [system_monitor.py:finish():190] Stopping system monitor
2023-09-15 23:28:36,972 DEBUG   SystemMonitor:2242593 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-09-15 23:28:36,979 DEBUG   SystemMonitor:2242593 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-09-15 23:28:36,979 DEBUG   SystemMonitor:2242593 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-09-15 23:28:36,972 INFO    HandlerThread:2242593 [interfaces.py:finish():202] Joined cpu monitor
2023-09-15 23:28:36,980 INFO    HandlerThread:2242593 [interfaces.py:finish():202] Joined disk monitor
2023-09-15 23:28:37,251 INFO    HandlerThread:2242593 [interfaces.py:finish():202] Joined gpu monitor
2023-09-15 23:28:37,251 INFO    HandlerThread:2242593 [interfaces.py:finish():202] Joined memory monitor
2023-09-15 23:28:37,251 INFO    HandlerThread:2242593 [interfaces.py:finish():202] Joined network monitor
2023-09-15 23:28:37,252 DEBUG   SenderThread:2242593 [sender.py:send_request():396] send_request: defer
2023-09-15 23:28:37,252 INFO    SenderThread:2242593 [sender.py:send_request_defer():598] handle sender defer: 2
2023-09-15 23:28:37,252 INFO    SenderThread:2242593 [sender.py:transition_state():602] send defer: 3
2023-09-15 23:28:37,252 DEBUG   SenderThread:2242593 [sender.py:send():369] send: stats
2023-09-15 23:28:37,252 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: defer
2023-09-15 23:28:37,252 INFO    HandlerThread:2242593 [handler.py:handle_request_defer():170] handle defer: 3
2023-09-15 23:28:37,252 DEBUG   SenderThread:2242593 [sender.py:send_request():396] send_request: defer
2023-09-15 23:28:37,252 INFO    SenderThread:2242593 [sender.py:send_request_defer():598] handle sender defer: 3
2023-09-15 23:28:37,252 INFO    SenderThread:2242593 [sender.py:transition_state():602] send defer: 4
2023-09-15 23:28:37,252 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: defer
2023-09-15 23:28:37,253 INFO    HandlerThread:2242593 [handler.py:handle_request_defer():170] handle defer: 4
2023-09-15 23:28:37,253 DEBUG   SenderThread:2242593 [sender.py:send_request():396] send_request: defer
2023-09-15 23:28:37,253 INFO    SenderThread:2242593 [sender.py:send_request_defer():598] handle sender defer: 4
2023-09-15 23:28:37,253 INFO    SenderThread:2242593 [sender.py:transition_state():602] send defer: 5
2023-09-15 23:28:37,253 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: defer
2023-09-15 23:28:37,253 INFO    HandlerThread:2242593 [handler.py:handle_request_defer():170] handle defer: 5
2023-09-15 23:28:37,253 DEBUG   SenderThread:2242593 [sender.py:send():369] send: summary
2023-09-15 23:28:37,255 INFO    SenderThread:2242593 [sender.py:_save_file():1354] saving file wandb-summary.json with policy end
2023-09-15 23:28:37,255 DEBUG   SenderThread:2242593 [sender.py:send_request():396] send_request: defer
2023-09-15 23:28:37,255 INFO    SenderThread:2242593 [sender.py:send_request_defer():598] handle sender defer: 5
2023-09-15 23:28:37,255 INFO    SenderThread:2242593 [sender.py:transition_state():602] send defer: 6
2023-09-15 23:28:37,255 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: defer
2023-09-15 23:28:37,255 INFO    HandlerThread:2242593 [handler.py:handle_request_defer():170] handle defer: 6
2023-09-15 23:28:37,256 DEBUG   SenderThread:2242593 [sender.py:send_request():396] send_request: defer
2023-09-15 23:28:37,256 INFO    SenderThread:2242593 [sender.py:send_request_defer():598] handle sender defer: 6
2023-09-15 23:28:37,260 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: status_report
2023-09-15 23:28:37,410 INFO    SenderThread:2242593 [sender.py:transition_state():602] send defer: 7
2023-09-15 23:28:37,410 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: defer
2023-09-15 23:28:37,410 INFO    HandlerThread:2242593 [handler.py:handle_request_defer():170] handle defer: 7
2023-09-15 23:28:37,411 DEBUG   SenderThread:2242593 [sender.py:send_request():396] send_request: defer
2023-09-15 23:28:37,411 INFO    SenderThread:2242593 [sender.py:send_request_defer():598] handle sender defer: 7
2023-09-15 23:28:37,968 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-15 23:28:38,675 INFO    SenderThread:2242593 [sender.py:transition_state():602] send defer: 8
2023-09-15 23:28:38,675 DEBUG   SenderThread:2242593 [sender.py:send_request():396] send_request: poll_exit
2023-09-15 23:28:38,676 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: defer
2023-09-15 23:28:38,676 INFO    HandlerThread:2242593 [handler.py:handle_request_defer():170] handle defer: 8
2023-09-15 23:28:38,676 DEBUG   SenderThread:2242593 [sender.py:send_request():396] send_request: defer
2023-09-15 23:28:38,676 INFO    SenderThread:2242593 [sender.py:send_request_defer():598] handle sender defer: 8
2023-09-15 23:28:38,676 INFO    SenderThread:2242593 [job_builder.py:build():232] Attempting to build job artifact
2023-09-15 23:28:38,677 INFO    SenderThread:2242593 [job_builder.py:build():256] is repo sourced job
2023-09-15 23:28:38,680 INFO    SenderThread:2242593 [job_builder.py:build():297] adding wandb-job metadata file
2023-09-15 23:28:38,697 INFO    SenderThread:2242593 [sender.py:transition_state():602] send defer: 9
2023-09-15 23:28:38,697 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: defer
2023-09-15 23:28:38,698 INFO    HandlerThread:2242593 [handler.py:handle_request_defer():170] handle defer: 9
2023-09-15 23:28:38,698 DEBUG   SenderThread:2242593 [sender.py:send():369] send: artifact
2023-09-15 23:28:38,969 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-15 23:28:40,088 INFO    wandb-upload_1:2242593 [upload_job.py:push():91] Uploaded file /home/userfs/j/jrs596/.local/share/wandb/artifacts/staging/tmpztkm4tx_
2023-09-15 23:28:40,092 INFO    wandb-upload_2:2242593 [upload_job.py:push():91] Uploaded file /home/userfs/j/jrs596/.local/share/wandb/artifacts/staging/tmp_439isb0
2023-09-15 23:28:41,545 INFO    SenderThread:2242593 [sender.py:send_artifact():1450] sent artifact job-git_github.com_jrsykes_Entangled.git_Torch_Custom_CNNs2.2.1.py - {'id': 'QXJ0aWZhY3Q6NTcwMTkzOTUz', 'digest': '7b57bc173308d59dcbd1e18d328cd87d', 'state': 'PENDING', 'aliases': [], 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjk3OTkxMDI5', 'latestArtifact': {'id': 'QXJ0aWZhY3Q6NTcwMTc4Mzcz', 'versionIndex': 0}}, 'version': 'latest'}
2023-09-15 23:28:41,545 DEBUG   SenderThread:2242593 [sender.py:send_request():396] send_request: defer
2023-09-15 23:28:41,545 INFO    SenderThread:2242593 [sender.py:send_request_defer():598] handle sender defer: 9
2023-09-15 23:28:41,545 INFO    SenderThread:2242593 [dir_watcher.py:finish():359] shutting down directory watcher
2023-09-15 23:28:43,970 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: keepalive
2023-09-15 23:28:48,971 DEBUG   HandlerThread:2242593 [handler.py:handle_request():144] handle_request: keepalive
2023-09-15 23:28:53,045 WARNING StreamThr :2242593 [internal.py:is_dead():414] Internal process exiting, parent pid 2241769 disappeared
2023-09-15 23:28:53,045 ERROR   StreamThr :2242593 [internal.py:wandb_internal():152] Internal process shutdown.
2023-09-15 23:28:53,971 INFO    WriterThread:2242593 [datastore.py:close():298] close: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230915_232828-mx8e5cga/run-mx8e5cga.wandb
2023-09-15 23:28:53,972 INFO    HandlerThread:2242593 [handler.py:finish():854] shutting down handler
2023-09-15 23:30:13,919 INFO    SenderThread:2242593 [dir_watcher.py:_on_file_modified():289] file/dir modified: /home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230915_232828-mx8e5cga/files/conda-environment.yaml
2023-09-15 23:30:13,919 ERROR   StreamThr :2242593 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "/local/scratch/jrs596/envs/torch3/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/local/scratch/jrs596/envs/torch3/lib/python3.10/site-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
    self._process(record)
  File "/local/scratch/jrs596/envs/torch3/lib/python3.10/site-packages/wandb/sdk/internal/internal.py", line 328, in _process
    self._sm.send(record)
  File "/local/scratch/jrs596/envs/torch3/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 376, in send
    send_handler(record)
  File "/local/scratch/jrs596/envs/torch3/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 398, in send_request
    send_handler(record)
  File "/local/scratch/jrs596/envs/torch3/lib/python3.10/site-packages/wandb/sdk/internal/sender.py", line 634, in send_request_defer
    self._dir_watcher.finish()
  File "/local/scratch/jrs596/envs/torch3/lib/python3.10/site-packages/wandb/filesync/dir_watcher.py", line 373, in finish
    self._file_observer.dispatch_events(
  File "/local/scratch/jrs596/envs/torch3/lib/python3.10/site-packages/wandb/vendor/watchdog_0_9_0/wandb_watchdog/observers/api.py", line 368, in dispatch_events
    handler.dispatch(event)
  File "/local/scratch/jrs596/envs/torch3/lib/python3.10/site-packages/wandb/vendor/watchdog_0_9_0/wandb_watchdog/events.py", line 454, in dispatch
    _method_map[event_type](event)
  File "/local/scratch/jrs596/envs/torch3/lib/python3.10/site-packages/wandb/filesync/dir_watcher.py", line 293, in _on_file_modified
    self._get_file_event_handler(event.src_path, save_name).on_modified()
  File "/local/scratch/jrs596/envs/torch3/lib/python3.10/site-packages/wandb/filesync/dir_watcher.py", line 167, in on_modified
    if self.current_size == 0:
  File "/local/scratch/jrs596/envs/torch3/lib/python3.10/site-packages/wandb/filesync/dir_watcher.py", line 133, in current_size
    return os.path.getsize(self.file_path)
  File "/local/scratch/jrs596/envs/torch3/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/userfs/j/jrs596/scripts/Entangled/wandb/run-20230915_232828-mx8e5cga/files/conda-environment.yaml'
2023-09-15 23:48:04,298 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: 502 Server Error: Bad Gateway for url: https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream. func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 01:31:46,945 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c842a6b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 01:33:11,268 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9840>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 01:34:04,366 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fa440>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 01:34:51,455 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9e70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 01:35:51,730 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 01:37:10,577 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9840>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 01:39:34,579 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fa440>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 01:42:40,805 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9e70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 01:47:58,753 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 01:53:50,381 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9840>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 02:00:19,768 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fa440>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 02:06:35,955 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9e70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 02:12:52,263 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 02:19:32,052 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9840>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 02:26:11,652 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fa440>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 02:32:51,565 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9e70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 02:38:42,490 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 04:46:37,039 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9840>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 04:47:24,014 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9ba0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 04:48:12,026 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9ae0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 04:49:05,836 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fbd00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 04:50:19,647 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9840>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 04:51:31,318 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9ba0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 04:53:14,478 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9ae0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 05:57:01,059 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fbd00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 05:58:31,579 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9f00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 05:59:23,561 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9de0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 06:00:18,327 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fa410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 06:01:27,263 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fbd00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 06:03:11,407 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9f00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 06:05:11,254 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9de0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 06:07:50,904 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fa410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 06:13:29,733 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fbd00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 06:19:38,164 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9f00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 06:25:59,292 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9de0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 06:32:16,072 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fa410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 06:38:18,825 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fbd00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 06:44:56,126 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9f00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 06:50:57,361 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9de0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 06:57:07,263 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fa410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 07:03:25,931 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fbd00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 07:09:27,055 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9f00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 07:15:40,166 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9de0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 07:21:28,342 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fa410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 07:27:15,868 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83fbd00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 07:33:56,357 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9f00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2023-09-16 07:39:45,300 WARNING FileStreamThread:2242593 [file_stream.py:request_with_retry():665] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/frankslab/Elodea/mx8e5cga/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f73c83f9de0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7f73c83677f0>>, args: ('https://api.wandb.ai/files/frankslab/Elodea/mx8e5cga/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
